name: health remind

on:
  schedule:
    - cron: '30 1-10 * * *'
  push:
    branches:
      - master

jobs:
  build:
    environment: TEST
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set env
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build remind
        run: mvn clean package -Dmaven.test.skip
      - name: run remind
        run: java -jar -Dding_url=${{ secrets.DING_URL }} -Donly_work_day=${{ secrets.ONLY_WORK }} -Dwork_url='${{ secrets.WORK_URL }}' -Dtest=${{ secrets.TEST }}  target/health-reminder-jar-with-dependencies.jar
