name: health remind

on:
  schedule:
    - cron: '30 9-18 * * *'
  push:
    branches:
      - master

jobs:
  build:
    env: TEST
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set env
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build remind
        run: mvn clean package -Dmaven.test.skip
      - name: run remind
        run: java -jar -Dding_url=${{ DING_URL }} -Donly_work_day=${{ ONLY_WORK }} -Dwork_url=${{ WORK_URL }} -Dtest=${{ TEST }}  target/health-reminder-jar-with-dependencies.jar
